name: Danger
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  danger:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clear Ruby cache
        run: |
          rm -rf ~/.ruby-version
          rm -rf ~/.rbenv
          rm -rf ~/.rvm
          rm -rf /usr/local/rvm
          rm -rf /opt/ruby

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: false

      - name: Check Ruby Version
        run: |
          ruby -v
          which ruby
          gem env

      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler:2.4.7
          bundle config set --local deployment 'false'
          bundle config set --local without ''
          bundle config set --local force_ruby_platform true
          bundle install --verbose

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger --verbose
